#服务器配置
server:
  port: 8090
#spring配置
spring:
  #数据源配置(默认数据源为HikariDataSource)
  datasource:
    #配置mysql数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:     
#配置mybatis框架
mybatis:
  #定义Mapper接口映射文件位置 
  mapper-locations: classpath:mapper/*.xml
  #定义实体类位置
  type-aliases-package: com.ssm.pojo
demo: 
  service: 
    version: 1.0.0  #自定义属性，版本号
dubbo:
  application:
    name: provider  #服务唯一ID，不要重复
  protocol:
    name: dubbo     #dubbo传输
    port: 20880     #端口默认20880
  registry:
  #zookeeper注册中心，我这是集群，从哪个地址进都一样，当然，为了容错性，把所有的都加上也行
    address: zookeeper://192.168.137.131:2181  
  provider:
    timeout: 1000    #提供者超时时间
#控制台打印sql语句
logging:
  level:
    com.ming.ssm.mapper: debug
